version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactiq-backend
    command: gunicorn bankinsight_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: transactiq-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: transactiq-db
    environment:
      POSTGRES_DB: bankinsightdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sushantno111
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
